# Generated by Django 4.1.3 on 2023-03-05 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("salones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detevento",
            name="cvedesgloseservicio",
            field=models.ForeignKey(
                db_column="CveDesgloseServicio",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="salones.desgloseservicio",
                verbose_name="Desglose",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldetevento",
            name="cvedesgloseservicio",
            field=models.ForeignKey(
                blank=True,
                db_column="CveDesgloseServicio",
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="salones.desgloseservicio",
                verbose_name="Desglose",
            ),
        ),
    ]
