# Generated by Django 4.1.3 on 2023-03-06 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("salones", "0002_alter_detevento_cvedesgloseservicio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parametros_imagenes",
            name="description",
        ),
        migrations.RemoveField(
            model_name="parametros_imagenes",
            name="height",
        ),
        migrations.RemoveField(
            model_name="parametros_imagenes",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="parametros_imagenes",
            name="width",
        ),
    ]
