# Generated by Django 4.1.3 on 2023-03-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salones", "0005_alter_parametros_imagenes_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="detevento",
            name="precio",
            field=models.FloatField(
                blank=True, db_column="Precio", null=True, verbose_name="Precio"
            ),
        ),
        migrations.AddField(
            model_name="historicaldetevento",
            name="precio",
            field=models.FloatField(
                blank=True, db_column="Precio", null=True, verbose_name="Precio"
            ),
        ),
        migrations.AlterField(
            model_name="detevento",
            name="nota",
            field=models.CharField(
                blank=True,
                db_column="Notas",
                default=None,
                max_length=200,
                null=True,
                verbose_name="Notas",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldetevento",
            name="nota",
            field=models.CharField(
                blank=True,
                db_column="Notas",
                default=None,
                max_length=200,
                null=True,
                verbose_name="Notas",
            ),
        ),
    ]
